name: CI

on:
  - push

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - double: x86_64-linux
            flake: bundled
            runner: ubuntu-latest
          - double: x86_64-darwin
            runner: macos-13
            flake: bundled
          - double: aarch64-darwin
            runner: macos-latest
            flake: bundled
          - double: x86_64-windows
            runner: ubuntu-latest
            flake: bundled-windows
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Build
        run: nix build -L .#${{ matrix.target.flake}}
      - name: Set interpreter
        if: ${{ matrix.target.double == 'x86_64-linux'}}
        run: |
          cp -rL result output
          rm -rf result
          chmod +w output/bin/d4
          nix run nixpkgs#patchelf -- --set-interpreter /lib64/ld-linux-x86-64.so.2 output/bin/d4
          chmod -w output/bin/d4
          mv output result
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: d4-${{ matrix.target.double }}
          path: result
